---
name: Check issues

on:
  workflow_dispatch:
  schedule:
    # Low activity: 23:00-08:00 UTC
    - cron: '41 0 * * 0'
    # - cron: '19 3 * * 1'
    # - cron: '53 5 * * 2'
    # - cron: '7 1 * * 3'
    # - cron: '29 6 * * 4'
    # - cron: '3 23 * * 4'
    # - cron: '47 4 * * 6'
  push:
    branches:
      - main
    paths:
      - .github/scripts/check_issues.py
      - .github/scripts/common.py
      - .github/workflows/check-issues.yaml

concurrency:
  group: git-auto-commit-action
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  check-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - env:
          GH_TOKEN: ${{ github.token }}
        run: .github/scripts/check_issues.py
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore: update issues status'
