---
name: Check sites

on:
  workflow_dispatch:
  schedule:
    # Low activity: 23:00-08:00 UTC
    - cron: '53 2 * * 0'
    # - cron: '31 0 * * 1'
    # - cron: '22 6 * * 2'
    # - cron: '13 7 * * 3'
    # - cron: '2 4 * * 4'
    # - cron: '51 5 * * 5'
    # - cron: '9 1 * * 6'
  push:
    branches:
      - main
    paths:
      - .github/scripts/check_sites.py
      - .github/scripts/common.py
      - .github/workflows/check-sites.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: .github/scripts/check_sites.py
      - uses: actions/checkout@v6
        with:
          clean: false
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore: update status'
